development:
      host: 127.0.0.1
      adapter: mysql
      database: c1
      port: 3306
      username: rblindore
#      password: foradian
      charset: unicode

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: foradian
cucumber:
  <<: *test
